### POST Request for EMAIL notification
POST http://localhost:8080/sendNotification
Content-Type: application/json

{
  "notificationtype": "EMAIL",
  "message": "This is a test message for EmailNotification"
}


### POST Request for SMS notification
POST http://localhost:8080/sendNotification
Content-Type: application/json

{
  "notificationtype": "SMS",
  "message": "This is a test message for SMSNotification"
}

### POST Request for PUSH notification
POST http://localhost:8080/sendNotification
Content-Type: application/json

{
  "notificationtype": "PUSH",
  "message": "This is a test message for PUSHNotification"
}

### POST Request for different notification type (should throw unknown notification type)
POST http://localhost:8080/sendNotification
Content-Type: application/json

{
  "notificationtype": "BLABLA",
  "message": "This is a test message for BLABLA"
}
